# 第_2_章_引言

## 来自 bit.ly 的 1.usa.gov 数据

In [13]:
path = '/Users/wonderful/Desktop/Data_Analysis_and_Finance_文件集合/pydata-book-master/ch02/usagov_bitly_data2012-03-16-1331923249.txt'

In [14]:
# 读取文件的第一行
open(path).readline()

'{ "a": "Mozilla\\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\\/535.11 (KHTML, like Gecko) Chrome\\/17.0.963.78 Safari\\/535.11", "c": "US", "nk": 1, "tz": "America\\/New_York", "gr": "MA", "g": "A6qOVH", "h": "wfLQtf", "l": "orofrog", "al": "en-US,en;q=0.8", "hh": "1.usa.gov", "r": "http:\\/\\/www.facebook.com\\/l\\/7AQEFzjSi\\/1.usa.gov\\/wfLQtf", "u": "http:\\/\\/www.ncbi.nlm.nih.gov\\/pubmed\\/22415991", "t": 1331923247, "hc": 1331822918, "cy": "Danvers", "ll": [ 42.576698, -70.954903 ] }\n'

In [15]:
# 用 json 模块将 JSON 字符串转换为字典对象
import json
path = '/Users/wonderful/Desktop/Data_Analysis_and_Finance_文件集合/pydata-book-master/ch02/usagov_bitly_data2012-03-16-1331923249.txt'
records = [json.loads(line) for line in open(path)]

In [16]:
records[0]

{'a': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.78 Safari/535.11',
 'al': 'en-US,en;q=0.8',
 'c': 'US',
 'cy': 'Danvers',
 'g': 'A6qOVH',
 'gr': 'MA',
 'h': 'wfLQtf',
 'hc': 1331822918,
 'hh': '1.usa.gov',
 'l': 'orofrog',
 'll': [42.576698, -70.954903],
 'nk': 1,
 'r': 'http://www.facebook.com/l/7AQEFzjSi/1.usa.gov/wfLQtf',
 't': 1331923247,
 'tz': 'America/New_York',
 'u': 'http://www.ncbi.nlm.nih.gov/pubmed/22415991'}

In [17]:
records[0]['tz'] # 给出的是字符串对戏那个形式

'America/New_York'

In [18]:
print(records[0]['tz'])

America/New_York

## 用纯 Python 代码对时区进行计数

In [19]:
time_zones = [rec['tz'] for rec in records if 'tz' in rec]

In [20]:
type(time_zones)

list

In [21]:
time_zones[:10]

['America/New_York',
 'America/Denver',
 'America/New_York',
 'America/Sao_Paulo',
 'America/New_York',
 'America/New_York',
 'Europe/Warsaw',
 '',
 '',
 '']

In [22]:
test_time_zones = {rec['tz'] for rec in records if 'tz' in rec}

In [23]:
type(test_time_zones)

set

In [24]:
test_time_zones

{'',
 'Africa/Cairo',
 'Africa/Casablanca',
 'Africa/Ceuta',
 'Africa/Johannesburg',
 'Africa/Lusaka',
 'America/Anchorage',
 'America/Argentina/Buenos_Aires',
 'America/Argentina/Cordoba',
 'America/Argentina/Mendoza',
 'America/Bogota',
 'America/Caracas',
 'America/Chicago',
 'America/Chihuahua',
 'America/Costa_Rica',
 'America/Denver',
 'America/Edmonton',
 'America/Guayaquil',
 'America/Halifax',
 'America/Indianapolis',
 'America/La_Paz',
 'America/Lima',
 'America/Los_Angeles',
 'America/Managua',
 'America/Mazatlan',
 'America/Mexico_City',
 'America/Monterrey',
 'America/Montevideo',
 'America/Montreal',
 'America/New_York',
 'America/Phoenix',
 'America/Puerto_Rico',
 'America/Rainy_River',
 'America/Recife',
 'America/Santo_Domingo',
 'America/Sao_Paulo',
 'America/St_Kitts',
 'America/Tegucigalpa',
 'America/Vancouver',
 'America/Winnipeg',
 'Asia/Amman',
 'Asia/Bangkok',
 'Asia/Beirut',
 'Asia/Calcutta',
 'Asia/Dubai',
 'Asia/Harbin',
 'Asia/Hong_Kong',
 'Asia/Istanbul',
 'Asia/Jakarta',
 'Asia/Jerusalem',
 'Asia/Karachi',
 'Asia/Kuala_Lumpur',
 'Asia/Kuching',
 'Asia/Manila',
 'Asia/Nicosia',
 'Asia/Novosibirsk',
 'Asia/Pontianak',
 'Asia/Riyadh',
 'Asia/Seoul',
 'Asia/Tokyo',
 'Asia/Yekaterinburg',
 'Australia/NSW',
 'Australia/Queensland',
 'Chile/Continental',
 'Europe/Amsterdam',
 'Europe/Athens',
 'Europe/Belgrade',
 'Europe/Berlin',
 'Europe/Bratislava',
 'Europe/Brussels',
 'Europe/Bucharest',
 'Europe/Budapest',
 'Europe/Copenhagen',
 'Europe/Dublin',
 'Europe/Helsinki',
 'Europe/Lisbon',
 'Europe/Ljubljana',
 'Europe/London',
 'Europe/Madrid',
 'Europe/Malta',
 'Europe/Moscow',
 'Europe/Oslo',
 'Europe/Paris',
 'Europe/Prague',
 'Europe/Riga',
 'Europe/Rome',
 'Europe/Skopje',
 'Europe/Sofia',
 'Europe/Stockholm',
 'Europe/Uzhgorod',
 'Europe/Vienna',
 'Europe/Vilnius',
 'Europe/Volgograd',
 'Europe/Warsaw',
 'Europe/Zurich',
 'Pacific/Auckland',
 'Pacific/Honolulu'}

In [25]:
def get_counts(sequence):
    counts= {}
    for x in sequence:
        if x in counts:
            counts[x] += 1
        else:
            counts[x] = 1
    return counts

In [26]:
from collections import defaultdict

def get_counts2(sequence):
    counts = defaultdict(int)
    for x in sequence:
        counts[x] += 1
    return counts

In [27]:
counts = get_counts(time_zones)

In [28]:
counts['America/New_York']

1251

In [29]:
len(time_zones)

3440

In [30]:
def top_counts(count_dict, n = 10):
    value_key_pairs = [(count, tz) for tz ,count in count_dict.items()]
    value_key_pairs.sort()
    return value_key_pairs[-n:]

In [31]:
top_counts(counts)

[(33, 'America/Sao_Paulo'),
 (35, 'Europe/Madrid'),
 (36, 'Pacific/Honolulu'),
 (37, 'Asia/Tokyo'),
 (74, 'Europe/London'),
 (191, 'America/Denver'),
 (382, 'America/Los_Angeles'),
 (400, 'America/Chicago'),
 (521, ''),
 (1251, 'America/New_York')]

In [32]:
def top_counts2(count_dict, n = 10):
    value_key_pairs = [(count, tz) for count, tz in count_dict.items()]
    value_key_pairs.sort()
    return value_key_pairs[-n:]

In [33]:
top_counts2(counts)

[('Europe/Sofia', 1),
 ('Europe/Stockholm', 14),
 ('Europe/Uzhgorod', 1),
 ('Europe/Vienna', 6),
 ('Europe/Vilnius', 2),
 ('Europe/Volgograd', 1),
 ('Europe/Warsaw', 16),
 ('Europe/Zurich', 4),
 ('Pacific/Auckland', 11),
 ('Pacific/Honolulu', 36)]

In [34]:
from collections import Counter

In [35]:
counts = Counter(time_zones)

In [36]:
counts.most_common(10)

[('America/New_York', 1251),
 ('', 521),
 ('America/Chicago', 400),
 ('America/Los_Angeles', 382),
 ('America/Denver', 191),
 ('Europe/London', 74),
 ('Asia/Tokyo', 37),
 ('Pacific/Honolulu', 36),
 ('Europe/Madrid', 35),
 ('America/Sao_Paulo', 33)]

## 用 pandas 对时区进行计数

In [37]:
from pandas import DataFrame, Series

In [38]:
import pandas as pd; import numpy as np

In [39]:
frame = DataFrame(records)

In [40]:
frame

,_heartbeat_,a,al,c,cy,g,gr,h,hc,hh,kw,l,ll,nk,r,t,tz,u
0,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,"en-US,en;q=0.8",US,Danvers,A6qOVH,MA,wfLQtf,1.331823e+09,1.usa.gov,NaN,orofrog,"[42.576698, -70.954903]",1.0,http://www.facebook.com/l/7AQEFzjSi/1.usa.gov/...,1.331923e+09,America/New_York,http://www.ncbi.nlm.nih.gov/pubmed/22415991
1,NaN,GoogleMaps/RochesterNY,NaN,US,Provo,mwszkS,UT,mwszkS,1.308262e+09,j.mp,NaN,bitly,"[40.218102, -111.613297]",0.0,http://www.AwareMap.com/,1.331923e+09,America/Denver,http://www.monroecounty.gov/etc/911/rss.php
2,NaN,Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...,en-US,US,Washington,xxr3Qb,DC,xxr3Qb,1.331920e+09,1.usa.gov,NaN,bitly,"[38.9007, -77.043098]",1.0,http://t.co/03elZC4Q,1.331923e+09,America/New_York,http://boxer.senate.gov/en/press/releases/0316...
3,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8)...,pt-br,BR,Braz,zCaLwp,27,zUtuOu,1.331923e+09,1.usa.gov,NaN,alelex88,"[-23.549999, -46.616699]",0.0,direct,1.331923e+09,America/Sao_Paulo,http://apod.nasa.gov/apod/ap120312.html
4,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,"en-US,en;q=0.8",US,Shrewsbury,9b6kNl,MA,9b6kNl,1.273672e+09,bit.ly,NaN,bitly,"[42.286499, -71.714699]",0.0,http://www.shrewsbury-ma.gov/selco/,1.331923e+09,America/New_York,http://www.shrewsbury-ma.gov/egov/gallery/1341...
5,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,"en-US,en;q=0.8",US,Shrewsbury,axNK8c,MA,axNK8c,1.273673e+09,bit.ly,NaN,bitly,"[42.286499, -71.714699]",0.0,http://www.shrewsbury-ma.gov/selco/,1.331923e+09,America/New_York,http://www.shrewsbury-ma.gov/egov/gallery/1341...
6,NaN,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.1...,"pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4",PL,Luban,wcndER,77,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,"[51.116699, 15.2833]",0.0,http://plus.url.google.com/url?sa=z&n=13319232...,1.331923e+09,Europe/Warsaw,http://www.nasa.gov/mission_pages/nustar/main/...
7,NaN,Mozilla/5.0 (Windows NT 6.1; rv:2.0.1) Gecko/2...,"bg,en-us;q=0.7,en;q=0.3",None,NaN,wcndER,NaN,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,NaN,0.0,http://www.facebook.com/,1.331923e+09,,http://www.nasa.gov/mission_pages/nustar/main/...
8,NaN,Opera/9.80 (X11; Linux zbov; U; en) Presto/2.1...,"en-US, en",None,NaN,wcndER,NaN,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,NaN,0.0,http://www.facebook.com/l.php?u=http%3A%2F%2F1...,1.331923e+09,,http://www.nasa.gov/mission_pages/nustar/main/...
9,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,"pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4",None,NaN,zCaLwp,NaN,zUtuOu,1.331923e+09,1.usa.gov,NaN,alelex88,NaN,0.0,http://t.co/o1Pd0WeV,1.331923e+09,,http://apod.nasa.gov/apod/ap120312.html
10,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:10.0.2)...,"en-us,en;q=0.5",US,Seattle,vNJS4H,WA,u0uD9q,1.319564e+09,1.usa.gov,NaN,o_4us71ccioa,"[47.5951, -122.332603]",1.0,direct,1.331923e+09,America/Los_Angeles,https://www.nysdot.gov/rexdesign/design/commun...
11,NaN,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.4...,"en-us,en;q=0.5",US,Washington,wG7OIH,DC,A0nRz4,1.331816e+09,1.usa.gov,NaN,darrellissa,"[38.937599, -77.092796]",0.0,http://t.co/ND7SoPyo,1.331923e+09,America/New_York,http://oversight.house.gov/wp-content/uploads/...
12,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:10.0.2)...,"en-us,en;q=0.5",US,Alexandria,vNJS4H,VA,u0uD9q,1.319564e+09,1.usa.gov,NaN,o_4us71ccioa,"[38.790901, -77.094704]",1.0,direct,1.331923e+09,America/New_York,https://www.nysdot.gov/rexdesign/design/commun...
13,1.331923e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US...,"en-us,en;q=0.5",US,Marietta,2rOUYc,GA,2rOUYc,1.255770e+09,1.usa.gov,NaN,bitly,"[33.953201, -84.5177]",1.0,direct,1.331923e+09,America/New_York,http://toxtown.nlm.nih.gov/index.php
15,NaN,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.1...,"zh-TW,zh;q=0.8,en-US;q=0.6,en;q=0.4",HK,Central District,nQvgJp,00,rtrrth,1.317318e+09,j.mp,NaN,walkeryuen,"[22.2833, 114.150002]",1.0,http://forum2.hkgolden.com/view.aspx?type=BW&m...,1.331923e+09,Asia/Hong_Kong,http://www.ssd.noaa.gov/PS/TROP/TCFP/data/curr...
16,NaN,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.1...,"zh-TW,zh;q=0.8,en-US;q=0.6,en;q=0.4",HK,Central District,XdUNr,00,qWkgbq,1.317318e+09,j.mp,NaN,walkeryuen,"[22.2833, 114.150002]",1.0,http://forum2.hkgolden.com/view.aspx?type=BW&m...,1.331923e+09,Asia/Hong_Kong,http://www.usno.navy.mil/NOOC/nmfc-ph/RSS/jtwc...
17,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; r...,"en-us,en;q=0.5",US,Buckfield,zH1BFf,ME,x3jOIv,1.331840e+09,1.usa.gov,NaN,andyzieminski,"[44.299702, -70.369797]",0.0,http://t.co/6Cx4ROLs,1.331923e+09,America/New_York,http://www.usda.gov/wps/portal/usda/usdahome?c...
18,NaN,GoogleMaps/RochesterNY,NaN,US,Provo,mwszkS,UT,mwszkS,1.308262e+09,1.usa.gov,NaN,bitly,"[40.218102, -111.613297]",0.0,http://www.AwareMap.com/,1.331923e+09,America/Denver,http://www.monroecounty.gov/etc/911/rss.php
19,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,"it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4",IT,Venice,wcndER,20,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,"[45.438599, 12.3267]",0.0,http://www.facebook.com/,1.331923e+09,Europe/Rome,http://www.nasa.gov/mission_pages/nustar/main/...
20,NaN,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,es-ES,ES,Alcal,zQ95Hi,51,ytZYWR,1.331671e+09,bitly.com,NaN,jplnews,"[37.516701, -5.9833]",0.0,http://www.facebook.com/,1.331923e+09,Africa/Ceuta,http://voyager.jpl.nasa.gov/imagesvideo/uranus...
21,NaN,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6...,"en-us,en;q=0.5",US,Davidsonville,wcndER,MD,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,"[38.939201, -76.635002]",0.0,http://www.facebook.com/,1.331923e+09,America/New_York,http://www.nasa.gov/mission_pages/nustar/main/...
22,NaN,Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...,en-us,US,Hockessin,y3ZImz,DE,y3ZImz,1.331064e+09,1.usa.gov,NaN,bitly,"[39.785, -75.682297]",0.0,direct,1.331923e+09,America/New_York,http://portal.hud.gov/hudportal/documents/hudd...
23,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3)...,en-us,US,Lititz,wWiOiD,PA,wWiOiD,1.330218e+09,1.usa.gov,NaN,bitly,"[40.174999, -76.3078]",0.0,http://www.facebook.com/l.php?u=http%3A%2F%2F1...,1.331923e+09,America/New_York,http://www.tricare.mil/mybenefit/ProfileFilter...
24,NaN,Mozilla/5.0 (Windows; U; Windows NT 5.1; es-ES...,"es-es,es;q=0.8,en-us;q=0.5,en;q=0.3",ES,Bilbao,wcndER,59,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,"[43.25, -2.9667]",0.0,http://www.facebook.com/,1.331923e+09,Europe/Madrid,http://www.nasa.gov/mission_pages/nustar/main/...
25,NaN,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.1...,"en-GB,en;q=0.8,en-US;q=0.6,en-AU;q=0.4",MY,Kuala Lumpur,wcndER,14,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,"[3.1667, 101.699997]",0.0,http://www.facebook.com/,1.331923e+09,Asia/Kuala_Lumpur,http://www.nasa.gov/mission_pages/nustar/main/...
26,NaN,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.1...,"ro-RO,ro;q=0.8,en-US;q=0.6,en;q=0.4",CY,Nicosia,wcndER,04,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,"[35.166698, 33.366699]",0.0,http://www.facebook.com/?ref=tn_tnmn,1.331923e+09,Asia/Nicosia,http://www.nasa.gov/mission_pages/nustar/main/...
27,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8)...,"en-US,en;q=0.8",BR,SPaulo,zCaLwp,27,zUtuOu,1.331923e+09,1.usa.gov,NaN,alelex88,"[-23.5333, -46.616699]",0.0,direct,1.331923e+09,America/Sao_Paulo,http://apod.nasa.gov/apod/ap120312.html
28,NaN,Mozilla/5.0 (iPad; CPU OS 5_0_1 like Mac OS X)...,en-us,None,NaN,vNJS4H,NaN,u0uD9q,1.319564e+09,1.usa.gov,NaN,o_4us71ccioa,NaN,0.0,direct,1.331923e+09,,https://www.nysdot.gov/rexdesign/design/commun...
29,NaN,Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X...,en-us,None,NaN,FPX0IM,NaN,FPX0IL,1.331923e+09,1.usa.gov,NaN,twittershare,NaN,1.0,http://t.co/5xlp0B34,1.331923e+09,,http://www.ed.gov/news/media-advisories/us-dep...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3530,NaN,Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.1...,"en-US,en;q=0.8",US,San Francisco,xVZg4P,CA,wqUkTo,1.331908e+09,go.nasa.gov,NaN,nasatwitter,"[37.7645, -122.429398]",0.0,http://www.facebook.com/l.php?u=http%3A%2F%2Fg...,1.331927e+09,America/Los_Angeles,http://www.nasa.gov/multimedia/imagegallery/im...
3531,NaN,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6...,en-US,None,NaN,wcndER,NaN,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,NaN,0.0,direct,1.331927e+09,,http://www.nasa.gov/mission_pages/nustar/main/...
3532,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:10.0.2)...,"en-us,en;q=0.5",US,Washington,Au3aUS,DC,A9ct6C,1.331926e+09,1.usa.gov,NaN,ncsha,"[38.904202, -77.031998]",1.0,http://www.ncsha.org/,1.331927e+09,America/New_York,http://portal.hud.gov/hudportal/HUD?src=/press...
3533,NaN,Mozilla/5.0 (iPad; CPU OS 5_1 like Mac OS X) A...,en-us,US,Jacksonville,b2UtUJ,FL,ieCdgH,1.301393e+09,go.nasa.gov,NaN,nasatwitter,"[30.279301, -81.585098]",1.0,direct,1.331927e+09,America/New_York,http://apod.nasa.gov/apod/
3534,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8)...,en-us,US,Frisco,vNJS4H,TX,u0uD9q,1.319564e+09,1.usa.gov,NaN,o_4us71ccioa,"[33.149899, -96.855499]",1.0,direct,1.331927e+09,America/Chicago,https://www.nysdot.gov/rexdesign/design/commun...
3535,NaN,Mozilla/5.0 (Windows NT 5.1; rv:10.0.2) Gecko/...,en-us,US,Houston,zIgLx8,TX,yrPaLt,1.331903e+09,aash.to,NaN,aashto,"[29.775499, -95.415199]",1.0,direct,1.331927e+09,America/Chicago,http://ntl.bts.gov/lib/44000/44300/44374/FHWA-...
3536,NaN,Mozilla/5.0 (BlackBerry; U; BlackBerry 9800; e...,"en-US,en;q=0.5",None,NaN,xIcyim,NaN,yG1TTf,1.331728e+09,go.nasa.gov,NaN,nasatwitter,NaN,0.0,http://t.co/g1VKE8zS,1.331927e+09,,http://www.nasa.gov/mission_pages/hurricanes/a...
3537,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:10.0.2)...,"es-es,es;q=0.8,en-us;q=0.5,en;q=0.3",HN,Tegucigalpa,zCaLwp,08,w63FZW,1.331547e+09,1.usa.gov,NaN,bufferapp,"[14.1, -87.216698]",0.0,http://t.co/A8TJyibE,1.331927e+09,America/Tegucigalpa,http://apod.nasa.gov/apod/ap120312.html
3538,NaN,Mozilla/5.0 (iPhone; CPU iPhone OS 5_1 like Ma...,en-us,US,Los Angeles,qMac9k,CA,qds1Ge,1.310474e+09,1.usa.gov,NaN,healthypeople,"[34.041599, -118.298798]",0.0,direct,1.331927e+09,America/Los_Angeles,http://healthypeople.gov/2020/connect/webinars...
3539,NaN,Mozilla/5.0 (compatible; Fedora Core 3) FC3 KDE,NaN,US,Bellevue,zu2M5o,WA,zDhdro,1.331586e+09,bit.ly,NaN,glimtwin,"[47.615398, -122.210297]",0.0,direct,1.331927e+09,America/Los_Angeles,http://www.federalreserve.gov/newsevents/press...
3540,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,"en-US,en;q=0.8",US,Payson,wcndER,UT,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,"[40.014198, -111.738899]",0.0,http://www.facebook.com/l.php?u=http%3A%2F%2F1...,1.331927e+09,America/Denver,http://www.nasa.gov/mission_pages/nustar/main/...
3541,NaN,Mozilla/5.0 (X11; U; OpenVMS AlphaServer_ES40;...,NaN,US,Bellevue,zu2M5o,WA,zDhdro,1.331586e+09,1.usa.gov,NaN,glimtwin,"[47.615398, -122.210297]",0.0,direct,1.331927e+09,America/Los_Angeles,http://www.federalreserve.gov/newsevents/press...
3542,NaN,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,en-us,US,Pittsburg,y3reI1,CA,y3reI1,1.331926e+09,1.usa.gov,NaN,bitly,"[38.0051, -121.838699]",0.0,http://www.facebook.com/l.php?u=http%3A%2F%2F1...,1.331927e+09,America/Los_Angeles,http://www.sba.gov/community/blogs/community-b...
3543,1.331927e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3544,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:5.0.1) ...,"en-us,en;q=0.5",US,Wentzville,vNJS4H,MO,u0uD9q,1.319564e+09,1.usa.gov,NaN,o_4us71ccioa,"[38.790001, -90.854897]",1.0,direct,1.331927e+09,America/Chicago,https://www.nysdot.gov/rexdesign/design/commun...
3545,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:10.0.2)...,"en-us,en;q=0.5",US,Saint Charles,vNJS4H,IL,u0uD9q,1.319564e+09,1.usa.gov,NaN,o_4us71ccioa,"[41.9352, -88.290901]",1.0,direct,1.331927e+09,America/Chicago,https://www.nysdot.gov/rexdesign/design/commun...
3546,NaN,Mozilla/5.0 (iPhone; CPU iPhone OS 5_1 like Ma...,en-us,US,Los Angeles,qMac9k,CA,qds1Ge,1.310474e+09,1.usa.gov,NaN,healthypeople,"[34.041599, -118.298798]",1.0,direct,1.331927e+09,America/Los_Angeles,http://healthypeople.gov/2020/connect/webinars...
3547,NaN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8)...,en-us,US,Silver Spring,y0jYkg,MD,y0jYkg,1.331852e+09,1.usa.gov,NaN,bitly,"[39.052101, -77.014999]",1.0,direct,1.331927e+09,America/New_York,http://www.epa.gov/otaq/regs/fuels/additive/e1...
3548,NaN,Mozilla/5.0 (iPhone; CPU iPhone OS 5_1 like Ma...,en-us,US,Mcgehee,y5rMac,AR,xANY6O,1.331916e+09,1.usa.gov,NaN,twitterfeed,"[33.628399, -91.356903]",1.0,https://twitter.com/fdarecalls/status/18069759...,1.331927e+09,America/Chicago,http://www.fda.gov/Safety/Recalls/ucm296326.htm
3549,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,"sv-SE,sv;q=0.8,en-US;q=0.6,en;q=0.4",SE,Sollefte,eH8wu,24,7dtjei,1.260316e+09,1.usa.gov,NaN,tweetdeckapi,"[63.166698, 17.266701]",1.0,direct,1.331927e+09,Europe/Stockholm,http://www.nasa.gov/mission_pages/WISE/main/in...
3550,NaN,Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...,en-us,US,Conshohocken,A00b72,PA,yGSwzn,1.331918e+09,1.usa.gov,NaN,addthis,"[40.0798, -75.2855]",0.0,http://www.linkedin.com/home?trk=hb_tab_home_top,1.331927e+09,America/New_York,http://www.nlm.nih.gov/medlineplus/news/fullst...
3551,NaN,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,"en-US,en;q=0.8",None,NaN,wcndER,NaN,zkpJBR,1.331923e+09,1.usa.gov,NaN,bnjacobs,NaN,0.0,http://plus.url.google.com/url?sa=z&n=13319268...,1.331927e+09,,http://www.nasa.gov/mission_pages/nustar/main/...
3552,NaN,Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US...,NaN,US,Decatur,rqgJuE,AL,xcz8vt,1.331227e+09,1.usa.gov,NaN,bootsnall,"[34.572701, -86.940598]",0.0,direct,1.331927e+09,America/Chicago,http://travel.state.gov/passport/passport_5535...
3553,NaN,Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...,en-us,US,Shrewsbury,9b6kNl,MA,9b6kNl,1.273672e+09,bit.ly,NaN,bitly,"[42.286499, -71.714699]",0.0,http://www.shrewsbury-ma.gov/selco/,1.331927e+09,America/New_York,http://www.shrewsbury-ma.gov/egov/gallery/1341...
3554,NaN,Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...,en-us,US,Shrewsbury,axNK8c,MA,axNK8c,1.273673e+09,bit.ly,NaN,bitly,"[42.286499, -71.714699]",0.0,http://www.shrewsbury-ma.gov/selco/,1.331927e+09,America/New_York,http://www.shrewsbury-ma.gov/egov/gallery/1341...
3555,NaN,Mozilla/4.0 (compatible; MSIE 9.0; Windows NT ...,en,US,Paramus,e5SvKE,NJ,fqPSr9,1.301298e+09,1.usa.gov,NaN,tweetdeckapi,"[40.9445, -74.07]",1.0,direct,1.331927e+09,America/New_York,http://www.fda.gov/AdvisoryCommittees/Committe...
3556,NaN,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.1...,"en-US,en;q=0.8",US,Oklahoma City,jQLtP4,OK,jQLtP4,1.307530e+09,1.usa.gov,NaN,bitly,"[35.4715, -97.518997]",0.0,http://www.facebook.com/l.php?u=http%3A%2F%2F1...,1.331927e+09,America/Chicago,http://www.okc.gov/PublicNotificationSystem/Fo...
3557,NaN,GoogleMaps/RochesterNY,NaN,US,Provo,mwszkS,UT,mwszkS,1.308262e+09,j.mp,NaN,bitly,"[40.218102, -111.613297]",0.0,http://www.AwareMap.com/,1.331927e+09,America/Denver,http://www.monroecounty.gov/etc/911/rss.php
3558,NaN,GoogleProducer,NaN,US,Mountain View,zjtI4X,CA,zjtI4X,1.327529e+09,1.usa.gov,NaN,bitly,"[37.419201, -122.057404]",0.0,direct,1.331927e+09,America/Los_Angeles,http://www.ahrq.gov/qual/qitoolkit/
3559,NaN,Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...,en-US,US,Mc Lean,qxKrTK,VA,qxKrTK,1.312898e+09,1.usa.gov,NaN,bitly,"[38.935799, -77.162102]",0.0,http://t.co/OEEEvwjU,1.331927e+09,America/New_York,http://herndon-va.gov/Content/public_safety/Pu...

In [41]:
tz_counts = frame['tz'].value_counts()

In [42]:
tz_counts[:10]

America/New_York       1251
                        521
America/Chicago         400
America/Los_Angeles     382
America/Denver          191
Europe/London            74
Asia/Tokyo               37
Pacific/Honolulu         36
Europe/Madrid            35
America/Sao_Paulo        33
Name: tz, dtype: int64

In [43]:
clean_tz = frame['tz'].fillna('Missing')

In [44]:
clean_tz[clean_tz == ''] = 'Uknown'

In [45]:
tz_counts = clean_tz.value_counts()

In [46]:
tz_counts[:10]

America/New_York       1251
Uknown                  521
America/Chicago         400
America/Los_Angeles     382
America/Denver          191
Missing                 120
Europe/London            74
Asia/Tokyo               37
Pacific/Honolulu         36
Europe/Madrid            35
Name: tz, dtype: int64

In [47]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib

In [48]:
tz_counts[:10].plot(kind='barh', rot=0)

In [49]:
frame['a'][1]

'GoogleMaps/RochesterNY'

In [50]:
frame['a'][50]

'Mozilla/5.0 (Windows NT 5.1; rv:10.0.2) Gecko/20100101 Firefox/10.0.2'

In [51]:
frame['a'][51]

'Mozilla/5.0 (Linux; U; Android 2.2.2; en-us; LG-P925/V10e Build/FRG83G) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1'

In [52]:
results = Series([x.split()[0] for x in frame.a.dropna()])

In [53]:
results[:5]

0               Mozilla/5.0
1    GoogleMaps/RochesterNY
2               Mozilla/4.0
3               Mozilla/5.0
4               Mozilla/5.0
dtype: object

In [54]:
results.value_counts()[:5]

Mozilla/5.0               2594
Mozilla/4.0                601
GoogleMaps/RochesterNY     121
Opera/9.80                  34
TEST_INTERNET_AGENT         24
dtype: int64

In [55]:
cframe = frame[frame.a.notnull()]

In [56]:
operating_system = np.where(cframe['a'].str.contains('Windows'), 'Windows', 'NOt Windows')

In [57]:
operating_system[:5]

array(['Windows', 'NOt Windows', 'Windows', 'NOt Windows', 'Windows'],
      dtype='<U11')

In [58]:
by_tz_os = cframe.groupby(['tz', operating_system])

In [59]:
agg_counts = by_tz_os.size().unstack().fillna(0)

In [60]:
agg_counts[:10]

                                NOt Windows  Windows
tz
                                      245.0    276.0
Africa/Cairo                            0.0      3.0
Africa/Casablanca                       0.0      1.0
Africa/Ceuta                            0.0      2.0
Africa/Johannesburg                     0.0      1.0
Africa/Lusaka                           0.0      1.0
America/Anchorage                       4.0      1.0
America/Argentina/Buenos_Aires          1.0      0.0
America/Argentina/Cordoba               0.0      1.0
America/Argentina/Mendoza               0.0      1.0

In [61]:
# 升序排列
indexer = agg_counts.sum(1).argsort()

In [62]:
indexer[:10]

tz
                                  24
Africa/Cairo                      20
Africa/Casablanca                 21
Africa/Ceuta                      92
Africa/Johannesburg               87
Africa/Lusaka                     53
America/Anchorage                 54
America/Argentina/Buenos_Aires    57
America/Argentina/Cordoba         26
America/Argentina/Mendoza         55
dtype: int64

In [63]:
count_subset = agg_counts.take(indexer)[-10:]

In [64]:
count_subset

                     NOt Windows  Windows
tz
America/Sao_Paulo           13.0     20.0
Europe/Madrid               16.0     19.0
Pacific/Honolulu             0.0     36.0
Asia/Tokyo                   2.0     35.0
Europe/London               43.0     31.0
America/Denver             132.0     59.0
America/Los_Angeles        130.0    252.0
America/Chicago            115.0    285.0
                           245.0    276.0
America/New_York           339.0    912.0

In [65]:
count_subset.plot(kind='barh', stacked=True)

In [66]:
normed_subset = count_subset.div(count_subset.sum(1), axis=0)

In [67]:
normed_subset.plot(kind='barh', stacked=True)

## MovieLens 1M 数据集

In [74]:
import pandas as pd

unames = ['user_id', 'gender', 'age', 'occupation', 'aip']
users = pd.read_table('/Users/wonderful/Desktop/Data_Analysis_and_Finance_文件集合/pydata-book-master/ch02/movielens/users.dat', sep = '::', header = None, names = unames)

rnames = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_table('/Users/wonderful/Desktop/Data_Analysis_and_Finance_文件集合/pydata-book-master/ch02/movielens/ratings.dat', sep = '::', header = None, names = rnames)

mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('/Users/wonderful/Desktop/Data_Analysis_and_Finance_文件集合/pydata-book-master/ch02/movielens/movies.dat', sep = '::', header = None, names = mnames)

/Users/wonderful/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
/Users/wonderful/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:7: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
/Users/wonderful/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:10: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [75]:
users[:5]

   user_id gender  age  occupation    aip
0        1      F    1          10  48067
1        2      M   56          16  70072
2        3      M   25          15  55117
3        4      M   45           7  02460
4        5      M   25          20  55455

In [76]:
ratings[:5]

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [77]:
movies[:5]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [78]:
ratings

         user_id  movie_id  rating  timestamp
0              1      1193       5  978300760
1              1       661       3  978302109
2              1       914       3  978301968
3              1      3408       4  978300275
4              1      2355       5  978824291
5              1      1197       3  978302268
6              1      1287       5  978302039
7              1      2804       5  978300719
8              1       594       4  978302268
9              1       919       4  978301368
10             1       595       5  978824268
11             1       938       4  978301752
12             1      2398       4  978302281
13             1      2918       4  978302124
14             1      1035       5  978301753
15             1      2791       4  978302188
16             1      2687       3  978824268
17             1      2018       4  978301777
18             1      3105       5  978301713
19             1      2797       4  978302039
20             1      2321       3  978302205
21             1       720       3  978300760
22             1      1270       5  978300055
23             1       527       5  978824195
24             1      2340       3  978300103
25             1        48       5  978824351
26             1      1097       4  978301953
27             1      1721       4  978300055
28             1      1545       4  978824139
29             1       745       3  978824268
...          ...       ...     ...        ...
1000179     6040      2762       4  956704584
1000180     6040      1036       3  956715455
1000181     6040       508       4  956704972
1000182     6040      1041       4  957717678
1000183     6040      3735       4  960971654
1000184     6040      2791       4  956715569
1000185     6040      2794       1  956716438
1000186     6040       527       5  956704219
1000187     6040      2003       1  956716294
1000188     6040       535       4  964828734
1000189     6040      2010       5  957716795
1000190     6040      2011       4  956716113
1000191     6040      3751       4  964828782
1000192     6040      2019       5  956703977
1000193     6040       541       4  956715288
1000194     6040      1077       5  964828799
1000195     6040      1079       2  956715648
1000196     6040       549       4  956704746
1000197     6040      2020       3  956715288
1000198     6040      2021       3  956716374
1000199     6040      2022       5  956716207
1000200     6040      2028       5  956704519
1000201     6040      1080       4  957717322
1000202     6040      1089       4  956704996
1000203     6040      1090       3  956715518
1000204     6040      1091       1  956716541
1000205     6040      1094       5  956704887
1000206     6040       562       5  956704746
1000207     6040      1096       4  956715648
1000208     6040      1097       4  956715569

[1000209 rows x 4 columns]

In [80]:
data = pd.merge(pd.merge(ratings, users), movies)

In [81]:
data

,user_id,movie_id,rating,timestamp,gender,age,occupation,aip,title,genres
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama
1,2,1193,5,978298413,M,56,16,70072,One Flew Over the Cuckoo's Nest (1975),Drama
2,12,1193,4,978220179,M,25,12,32793,One Flew Over the Cuckoo's Nest (1975),Drama
3,15,1193,4,978199279,M,25,7,22903,One Flew Over the Cuckoo's Nest (1975),Drama
4,17,1193,5,978158471,M,50,1,95350,One Flew Over the Cuckoo's Nest (1975),Drama
5,18,1193,4,978156168,F,18,3,95825,One Flew Over the Cuckoo's Nest (1975),Drama
6,19,1193,5,982730936,M,1,10,48073,One Flew Over the Cuckoo's Nest (1975),Drama
7,24,1193,5,978136709,F,25,7,10023,One Flew Over the Cuckoo's Nest (1975),Drama
8,28,1193,3,978125194,F,25,1,14607,One Flew Over the Cuckoo's Nest (1975),Drama
9,33,1193,5,978557765,M,45,3,55421,One Flew Over the Cuckoo's Nest (1975),Drama
10,39,1193,5,978043535,M,18,4,61820,One Flew Over the Cuckoo's Nest (1975),Drama
11,42,1193,3,978038981,M,25,8,24502,One Flew Over the Cuckoo's Nest (1975),Drama
12,44,1193,4,978018995,M,45,17,98052,One Flew Over the Cuckoo's Nest (1975),Drama
13,47,1193,4,977978345,M,18,4,94305,One Flew Over the Cuckoo's Nest (1975),Drama
14,48,1193,4,977975061,M,25,4,92107,One Flew Over the Cuckoo's Nest (1975),Drama
15,49,1193,4,978813972,M,18,12,77084,One Flew Over the Cuckoo's Nest (1975),Drama
16,53,1193,5,977946400,M,25,0,96931,One Flew Over the Cuckoo's Nest (1975),Drama
17,54,1193,5,977944039,M,50,1,56723,One Flew Over the Cuckoo's Nest (1975),Drama
18,58,1193,5,977933866,M,25,2,30303,One Flew Over the Cuckoo's Nest (1975),Drama
19,59,1193,4,977934292,F,50,1,55413,One Flew Over the Cuckoo's Nest (1975),Drama
20,62,1193,4,977968584,F,35,3,98105,One Flew Over the Cuckoo's Nest (1975),Drama
21,80,1193,4,977786172,M,56,1,49327,One Flew Over the Cuckoo's Nest (1975),Drama
22,81,1193,5,977785864,F,25,0,60640,One Flew Over the Cuckoo's Nest (1975),Drama
23,88,1193,5,977694161,F,45,1,02476,One Flew Over the Cuckoo's Nest (1975),Drama
24,89,1193,5,977683596,F,56,9,85749,One Flew Over the Cuckoo's Nest (1975),Drama
25,95,1193,5,977626632,M,45,0,98201,One Flew Over the Cuckoo's Nest (1975),Drama
26,96,1193,3,977621789,F,25,16,78028,One Flew Over the Cuckoo's Nest (1975),Drama
27,99,1193,2,982791053,F,1,10,19390,One Flew Over the Cuckoo's Nest (1975),Drama
28,102,1193,5,1040737607,M,35,19,20871,One Flew Over the Cuckoo's Nest (1975),Drama
29,104,1193,2,977546620,M,25,12,00926,One Flew Over the Cuckoo's Nest (1975),Drama
...,...,...,...,...,...,...,...,...,...,...
1000179,4933,3084,3,962757020,M,25,15,94040,Home Page (1999),Documentary
1000180,4802,2218,2,1014866656,M,56,1,40601,Juno and Paycock (1930),Drama
1000181,4812,2308,2,962932391,M,18,14,25301,Detroit 9000 (1973),Action|Crime
1000182,4874,624,4,962781918,F,25,4,70808,Condition Red (1995),Action|Drama|Thriller
1000183,5059,1434,4,962484364,M,45,16,22652,"Stranger, The (1994)",Action
1000184,5947,1434,4,957190428,F,45,16,97215,"Stranger, The (1994)",Action
1000185,5077,1868,3,962417299,M,25,2,20037,"Truce, The (1996)",Drama|War
1000186,5944,1868,1,957197520,F,18,10,27606,"Truce, The (1996)",Drama|War
1000187,5105,404,3,962337582,M,50,7,18977,Brother Minister: The Assassination of Malcolm...,Documentary
1000188,5185,404,4,963402617,F,35,4,44485,Brother Minister: The Assassination of Malcolm...,Documentary
1000189,5532,404,5,959619841,M,25,17,27408,Brother Minister: The Assassination of Malcolm...,Documentary
1000190,5543,404,3,960127592,M,25,17,97401,Brother Minister: The Assassination of Malcolm...,Documentary
1000191,5220,2543,3,961546137,M,25,7,91436,Six Ways to Sunday (1997),Comedy
1000192,5754,2543,4,958272316,F,18,1,60640,Six Ways to Sunday (1997),Comedy
1000193,5227,591,3,961475931,M,18,10,64050,Tough and Deadly (1995),Action|Drama|Thriller
1000194,5795,591,1,958145253,M,25,1,92688,Tough and Deadly (1995),Action|Drama|Thriller
1000195,5313,3656,5,960920392,M,56,0,55406,Lured (1947),Crime
1000196,5328,2438,4,960838075,F,25,4,91740,Outside Ozona (1998),Drama|Thriller
1000197,5334,3323,3,960796159,F,56,13,46140,Chain of Fools (2000),Comedy|Crime
1000198,5334,127,1,960795494,F,56,13,46140,"Silence of the Palace, The (Saimt el Qusur) (1...",Drama
1000199,5334,3382,5,960796159,F,56,13,46140,Song of Freedom (1936),Drama
1000200,5420,1843,3,960156505,F,1,19,14850,Slappy and the Stinkers (1998),Children's|Comedy
1000201,5433,286,3,960240881,F,35,17,45014,Nemesis 2: Nebula (1995),Action|Sci-Fi|Thriller
1000202,5494,3530,4,959816296,F,35,17,94306,Smoking/No Smoking (1993),Comedy
1000203,5556,2198,3,959445515,M,45,6,92103,Modulations (1998),Documentary
1000204,5949,2198,5,958846401,M,18,17,47901,Modulations (1998),Documentary
1000205,5675,2703,3,976029116,M,35,14,30030,Broken Vessels (1998),Drama
1000206,5780,2845,1,958153068,M,18,17,92886,White Boys (1999),Drama
1000207,5851,3607,5,957756608,F,18,20,55410,One Little Indian (1973),Comedy|Drama|Western
1000208,5938,2909,4,957273353,M,25,1,35401,"Five Wives, Three Secretaries and Me (1998)",Documentary

In [82]:
data.ix[0]

user_id                                            1
movie_id                                        1193
rating                                             5
timestamp                                  978300760
gender                                             F
age                                                1
occupation                                        10
aip                                            48067
title         One Flew Over the Cuckoo's Nest (1975)
genres                                         Drama
Name: 0, dtype: object

In [85]:
help(data.pivot_table)
#  ['pɪvət] vt. 以…为中心旋转；把…置于枢轴上

Help on method pivot_table in module pandas.tools.pivot:

pivot_table(values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All') method of pandas.core.frame.DataFrame instance
    Create a spreadsheet-style pivot table as a DataFrame. The levels in the
    pivot table will be stored in MultiIndex objects (hierarchical indexes) on
    the index and columns of the result DataFrame

    Parameters
    ----------
    data : DataFrame
    values : column to aggregate, optional
    index : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The list
        can contain any of the other types (except list).
        Keys to group by on the pivot table index.  If an array is passed, it
        is being used as the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The list
        can contain any of the other types (except list).
        Keys to group by on the pivot table column.  If an array is passed, it
        is being used as the same manner as column values.
    aggfunc : function or list of functions, default numpy.mean
        If list of functions passed, the resulting pivot table will have
        hierarchical columns whose top level are the function names (inferred
        from the function objects themselves)
    fill_value : scalar, default None
        Value to replace missing values with
    margins : boolean, default False
        Add all row / columns (e.g. for subtotal / grand totals)
    dropna : boolean, default True
        Do not include columns whose entries are all NaN
    margins_name : string, default 'All'
        Name of the row / column that will contain the totals
        when margins is True.

    Examples
    --------
    >>> df
       A   B   C      D
    0  foo one small  1
    1  foo one large  2
    2  foo one large  2
    3  foo two small  3
    4  foo two small  3
    5  bar one large  4
    6  bar one small  5
    7  bar two small  6
    8  bar two large  7

    >>> table = pivot_table(df, values='D', index=['A', 'B'],
    ...                     columns=['C'], aggfunc=np.sum)
    >>> table
              small  large
    foo  one  1      4
         two  6      NaN
    bar  one  5      4
         two  6      7

    Returns
    -------
    table : DataFrame

In [91]:
mean_ratings = data.pivot_table(values='rating', index='title', columns='gender', aggfunc='mean')
# mean_ratings = data.pivot_table('rating', rows='title', cols='gender', aggfunc='mean')
# 计算均分的对象是“ratings”，index 是“title”，分类的对象是“gender”

In [92]:
mean_ratings[:5]

gender                                F         M
title
$1,000,000 Duck (1971)         3.375000  2.761905
'Night Mother (1986)           3.388889  3.352941
'Til There Was You (1997)      2.675676  2.733333
'burbs, The (1989)             2.793478  2.962085
...And Justice for All (1979)  3.828571  3.689024

In [93]:
ratings_by_title = data.groupby('title').size()

In [94]:
ratings_by_title[:10]

title
$1,000,000 Duck (1971)                37
'Night Mother (1986)                  70
'Til There Was You (1997)             52
'burbs, The (1989)                   303
...And Justice for All (1979)        199
1-900 (1994)                           2
10 Things I Hate About You (1999)    700
101 Dalmatians (1961)                565
101 Dalmatians (1996)                364
12 Angry Men (1957)                  616
dtype: int64

In [95]:
help(data.groupby)

Help on method groupby in module pandas.core.generic:

groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, **kwargs) method of pandas.core.frame.DataFrame instance
    Group series using mapper (dict or key function, apply given function
    to group, return result as series) or by a series of columns.

    Parameters
    ----------
    by : mapping function / list of functions, dict, Series, or tuple /
        list of column names.
        Called on each element of the object index to determine the groups.
        If a dict or Series is passed, the Series or dict VALUES will be
        used to determine the groups
    axis : int, default 0
    level : int, level name, or sequence of such, default None
        If the axis is a MultiIndex (hierarchical), group by a particular
        level or levels
    as_index : boolean, default True
        For aggregated output, return object with group labels as the
        index. Only relevant for DataFrame input. as_index=False is
        effectively "SQL-style" grouped output
    sort : boolean, default True
        Sort group keys. Get better performance by turning this off.
        Note this does not influence the order of observations within each
        group.  groupby preserves the order of rows within each group.
    group_keys : boolean, default True
        When calling apply, add group keys to index to identify pieces
    squeeze : boolean, default False
        reduce the dimensionality of the return type if possible,
        otherwise return a consistent type

    Examples
    --------
    DataFrame results

    >>> data.groupby(func, axis=0).mean()
    >>> data.groupby(['col1', 'col2'])['col3'].mean()

    DataFrame with hierarchical index

    >>> data.groupby(['col1', 'col2']).mean()

    Returns
    -------
    GroupBy object

In [96]:
active_titles = ratings_by_title.index[ratings_by_title >= 250]

In [98]:
active_titles

Index([''burbs, The (1989)', '10 Things I Hate About You (1999)',
       '101 Dalmatians (1961)', '101 Dalmatians (1996)', '12 Angry Men (1957)',
       '13th Warrior, The (1999)', '2 Days in the Valley (1996)',
       '20,000 Leagues Under the Sea (1954)', '2001: A Space Odyssey (1968)',
       '2010 (1984)',
       ...
       'X-Men (2000)', 'Year of Living Dangerously (1982)',
       'Yellow Submarine (1968)', 'You've Got Mail (1998)',
       'Young Frankenstein (1974)', 'Young Guns (1988)',
       'Young Guns II (1990)', 'Young Sherlock Holmes (1985)',
       'Zero Effect (1998)', 'eXistenZ (1999)'],
      dtype='object', name='title', length=1216)

In [99]:
mean_ratings = mean_ratings.ix[active_titles]

In [100]:
mean_ratings

gender                                                     F         M
title
'burbs, The (1989)                                  2.793478  2.962085
10 Things I Hate About You (1999)                   3.646552  3.311966
101 Dalmatians (1961)                               3.791444  3.500000
101 Dalmatians (1996)                               3.240000  2.911215
12 Angry Men (1957)                                 4.184397  4.328421
13th Warrior, The (1999)                            3.112000  3.168000
2 Days in the Valley (1996)                         3.488889  3.244813
20,000 Leagues Under the Sea (1954)                 3.670103  3.709205
2001: A Space Odyssey (1968)                        3.825581  4.129738
2010 (1984)                                         3.446809  3.413712
28 Days (2000)                                      3.209424  2.977707
39 Steps, The (1935)                                3.965517  4.107692
54 (1998)                                           2.701754  2.782178
7th Voyage of Sinbad, The (1958)                    3.409091  3.658879
8MM (1999)                                          2.906250  2.850962
About Last Night... (1986)                          3.188679  3.140909
Absent Minded Professor, The (1961)                 3.469388  3.446809
Absolute Power (1997)                               3.469136  3.327759
Abyss, The (1989)                                   3.659236  3.689507
Ace Ventura: Pet Detective (1994)                   3.000000  3.197917
Ace Ventura: When Nature Calls (1995)               2.269663  2.543333
Addams Family Values (1993)                         3.000000  2.878531
Addams Family, The (1991)                           3.186170  3.163498
Adventures in Babysitting (1987)                    3.455782  3.208122
Adventures of Buckaroo Bonzai Across the 8th Di...  3.308511  3.402321
Adventures of Priscilla, Queen of the Desert, T...  3.989071  3.688811
Adventures of Robin Hood, The (1938)                4.166667  3.918367
African Queen, The (1951)                           4.324232  4.223822
Age of Innocence, The (1993)                        3.827068  3.339506
Agnes of God (1985)                                 3.534884  3.244898
...                                                      ...       ...
White Men Can't Jump (1992)                         3.028777  3.231061
Who Framed Roger Rabbit? (1988)                     3.569378  3.713251
Who's Afraid of Virginia Woolf? (1966)              4.029703  4.096939
Whole Nine Yards, The (2000)                        3.296552  3.404814
Wild Bunch, The (1969)                              3.636364  4.128099
Wild Things (1998)                                  3.392000  3.459082
Wild Wild West (1999)                               2.275449  2.131973
William Shakespeare's Romeo and Juliet (1996)       3.532609  3.318644
Willow (1988)                                       3.658683  3.453543
Willy Wonka and the Chocolate Factory (1971)        4.063953  3.789474
Witness (1985)                                      4.115854  3.941504
Wizard of Oz, The (1939)                            4.355030  4.203138
Wolf (1994)                                         3.074074  2.899083
Women on the Verge of a Nervous Breakdown (1988)    3.934307  3.865741
Wonder Boys (2000)                                  4.043796  3.913649
Working Girl (1988)                                 3.606742  3.312500
World Is Not Enough, The (1999)                     3.337500  3.388889
Wrong Trousers, The (1993)                          4.588235  4.478261
Wyatt Earp (1994)                                   3.147059  3.283898
X-Files: Fight the Future, The (1998)               3.489474  3.493797
X-Men (2000)                                        3.682310  3.851702
Year of Living Dangerously (1982)                   3.951220  3.869403
Yellow Submarine (1968)                             3.714286  3.689286
You've Got Mail (1998)                              3.542424  3.275591
Young Frankenstein (1974)                           4.289963  4.239177
Young Guns (1988)                                   3.371795  3.425620
Young Guns II (1990)                                2.934783  2.904025
Young Sherlock Holmes (1985)                        3.514706  3.363344
Zero Effect (1998)                                  3.864407  3.723140
eXistenZ (1999)                                     3.098592  3.289086

[1216 rows x 2 columns]

In [101]:
top_female_ratings = mean_ratings.sort_index(by='F', ascending=False)

/Users/wonderful/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':

In [102]:
top_female_ratings[:10]

gender                                                     F         M
title
Close Shave, A (1995)                               4.644444  4.473795
Wrong Trousers, The (1993)                          4.588235  4.478261
Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)       4.572650  4.464589
Wallace & Gromit: The Best of Aardman Animation...  4.563107  4.385075
Schindler's List (1993)                             4.562602  4.491415
Shawshank Redemption, The (1994)                    4.539075  4.560625
Grand Day Out, A (1992)                             4.537879  4.293255
To Kill a Mockingbird (1962)                        4.536667  4.372611
Creature Comforts (1990)                            4.513889  4.272277
Usual Suspects, The (1995)                          4.513317  4.518248

### 计算评分分歧

In [103]:
mean_ratings['diff'] = mean_ratings['M'] - mean_ratings['F']

In [104]:
sorted_by_diff = mean_ratings.sort_index(by='diff')

/Users/wonderful/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':

In [105]:
sorted_by_diff[:15]

gender                                        F         M      diff
title
Dirty Dancing (1987)                   3.790378  2.959596 -0.830782
Jumpin' Jack Flash (1986)              3.254717  2.578358 -0.676359
Grease (1978)                          3.975265  3.367041 -0.608224
Little Women (1994)                    3.870588  3.321739 -0.548849
Steel Magnolias (1989)                 3.901734  3.365957 -0.535777
Anastasia (1997)                       3.800000  3.281609 -0.518391
Rocky Horror Picture Show, The (1975)  3.673016  3.160131 -0.512885
Color Purple, The (1985)               4.158192  3.659341 -0.498851
Age of Innocence, The (1993)           3.827068  3.339506 -0.487561
Free Willy (1993)                      2.921348  2.438776 -0.482573
French Kiss (1995)                     3.535714  3.056962 -0.478752
Little Shop of Horrors, The (1960)     3.650000  3.179688 -0.470312
Guys and Dolls (1955)                  4.051724  3.583333 -0.468391
Mary Poppins (1964)                    4.197740  3.730594 -0.467147
Patch Adams (1998)                     3.473282  3.008746 -0.464536

In [106]:
sorted_by_diff[::-1][:15]

gender                                         F         M      diff
title
Good, The Bad and The Ugly, The (1966)  3.494949  4.221300  0.726351
Kentucky Fried Movie, The (1977)        2.878788  3.555147  0.676359
Dumb & Dumber (1994)                    2.697987  3.336595  0.638608
Longest Day, The (1962)                 3.411765  4.031447  0.619682
Cable Guy, The (1996)                   2.250000  2.863787  0.613787
Evil Dead II (Dead By Dawn) (1987)      3.297297  3.909283  0.611985
Hidden, The (1987)                      3.137931  3.745098  0.607167
Rocky III (1982)                        2.361702  2.943503  0.581801
Caddyshack (1980)                       3.396135  3.969737  0.573602
For a Few Dollars More (1965)           3.409091  3.953795  0.544704
Porky's (1981)                          2.296875  2.836364  0.539489
Animal House (1978)                     3.628906  4.167192  0.538286
Exorcist, The (1973)                    3.537634  4.067239  0.529605
Fright Night (1985)                     2.973684  3.500000  0.526316
Barb Wire (1996)                        1.585366  2.100386  0.515020

In [111]:
rating_std_by_title = data.groupby('title')['rating'].std()

In [113]:
rating_std_by_title = rating_std_by_title.ix[active_titles]

In [116]:
rating_std_by_title.order(ascending=False)[:10]

/Users/wonderful/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: order is deprecated, use sort_values(...)
  if __name__ == '__main__':

title
Dumb & Dumber (1994)                     1.321333
Blair Witch Project, The (1999)          1.316368
Natural Born Killers (1994)              1.307198
Tank Girl (1995)                         1.277695
Rocky Horror Picture Show, The (1975)    1.260177
Eyes Wide Shut (1999)                    1.259624
Evita (1996)                             1.253631
Billy Madison (1995)                     1.249970
Fear and Loathing in Las Vegas (1998)    1.246408
Bicentennial Man (1999)                  1.245533
Name: rating, dtype: float64